version: "3.7"
services: 
  oracle-server-db:
    container_name: oracle-server-db
    image: gvenzl/oracle-xe
    ports: 
      - "${DATABASE_EXPOSE_PORT}:${DATABASE_PORT}"
    environment:
      ORACLE_PASSWORD: "${ORACLE_PASSWORD}"
